apiVersion: v1
kind: PersistentVolume
metadata:
  name: kvar-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/bon_srik117/kimai2/var"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kvar-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
