apiVersion: v1
kind: PersistentVolume
metadata:
  name: kpub-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/bon_srik117/kimai2/public"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kpub-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  selector:
    matchLabels:
      type: local
